# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190210_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('value', models.FloatField()),
                ('method', models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Unknown')])),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
    ]
