# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 04:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190210_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='alivetoken',
            name='local',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
    ]
